# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"number_sum": "00_core.ipynb",
         "lettermax": "00_core.ipynb",
         "numwords": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://BrendaLPhys.github.io/numbers_in_text/"

git_url = "https://github.com/BrendaLPhys/numbers_in_text/tree/master/"

def custom_doc_links(name): return None
