# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['number_sum', 'lettermax', 'numwords']

# Cell

def number_sum(text):
    import re
    for line in text:
        y = re.findall("[0-9]+", text)
    sums = 0
    for list in y:
        number = int(list)
        sums = sums + number
    print('The total is:', sums)

# Cell

def lettermax(text):

    counts = dict()

    for line in text:
        words = line.split()
        for word in words:
            counts[word] = counts.get(word, 0) + 1

    bigcount = None
    bigword = None
    for word, count in list(counts.items()):
        if bigcount is None or count > bigcount:
            bigword = word
            bigcount = count

    print('The letter used the most is: ',bigword, ', it was used used: ', bigcount, ' times.')

# Cell

def numwords(text):
    count = 0
    for word in text:
        count += 1
    print("Total number of words is:", count)